'use strict';

var RESOURCE = {
    TEXT0: 'Godam',
    TEXT1: 'ASN',
    TEXT2: 'Batch',
    TEXT3: 'batch',
    TEXT4: 'number',
    TEXT5: 'Client',
    TEXT6: 'store',
    TEXT7: 'client',
    TEXT8: 'Supplier',
    TEXT9: 'supplier',
    TEXT10: 'Create',
    TEXT11: 'Manage',
    TEXT12: 'Receiving',
    TEXT13: 'Quality Check',
    TEXT15: 'Item',
    TEXT16: 'Check Item',
    TEXT17: 'Warning',
    TEXT18: 'Serial number',
    TEXT19: 'Product',
    TEXT20: 'Channel',
    TEXT21: 'Mapping',
    TEXT23: 'Put items',
    TEXT24: 'party',
    TEXT25: 'master',
    TEXT26: 'channel',
    S: 's',
};

angular.module('wmsApp')
    .constant('langEN', {
        en: {
            LANGUAGE_LIST: {
                LANG_SELECTED: 'English (India)',
                LANG1: 'English (India)',
                LANG2: 'Arabic (Dubai)',
                LANG3: 'Malay (Malaysia)',
                LANG4: 'Tamil (Srilanka)'
            },
            LOGIN_PAGE: {
                PAGE_TITLE: RESOURCE.TEXT0 + ' | Login',
                ERR1: 'Invalid user name or password.',
            },
            HOME_PAGE: {
                PAGE_TITLE: RESOURCE.TEXT0 + ' | Home',
                P1: 'If you do not have Delhivery ID,',
                GOOGLE_AUTH_SUCC_MSG: 'Thank you for registering with ' + RESOURCE.TEXT0 + '.<br/>You can start using the application when',
                GOOGLE_AUTH_SUCC_MSG1: 'your profile is approved by the administrator.',
                MAIL_TEXT: 'Please mail to',
                QUERY_TEXT: 'for any queries.',
                GOOGLE_AUTH_ERR_MSG: 'Oops! Looks like you did not allow us to check <br>your Google email address and basic profile information',
                GOOGLE_AUTH_ERR_MSG1: 'Please try again.',
                CLICK_LOGIN_TEXT: 'Click here to login'
            },
            FORGOT_PASSWORD_PAGE: {
                PAGE_TITLE: RESOURCE.TEXT0 + ' | Forgot Password',
                H1: 'Please enter your new password',
                P1: 'Password reset mail sent!',
                CLICK_LOGIN_TEXT: 'Click here to Login',
                PLACEHOLDER_TEXT: 'Enter email',
                ERR2: 'Email address too long.',
                ERR3: 'Enter a valid email. For example, xyz@xyz.com',
                ERR4: 'Error occurred, please contact admin'
            },
            RESET_PASSWORD_PAGE: {
                PAGE_TITLE: RESOURCE.TEXT0 + ' | Reset Password',
                CONFIRM_PASSWORD_TEXT: 'Re-enter new password',
                NEW_PASSWORD_TEXT: 'New password'
            },
            CHANGE_PASSWORD_PAGE: {
                PAGE_TITLE: RESOURCE.TEXT0 + ' | Change Password',
                CHANGE_PASSWORD_TEXT: 'Change Password',
                NEW_PASSWORD: 'New password',
                CURRENT_PASSWORD: 'Current password',
                CONFIRM_PASSWORD: 'Confirm new password',
                CHANGE_PASS: 'Change',
                P1: 'Password changed successfully',
                P2: 'Taking you to the login page in <time> seconds',
                ERR1: 'New password and confirm password do not match.'
            },
            LEFT_MENU: {
                RCV: {
                    MAIN_MENU: 'Receiving',
                    SUB_MENU_TEXT1: 'Create ASN',
                    SUB_MENU_TEXT2: 'ASN',
                    SUB_MENU_TEXT3: 'Batches',
                    SUB_MENU_TEXT4: 'Receive incoming shipment',
                    SUB_MENU_TEXT5: 'Receive arrived items',
                },
                RO: {
                    RO_TEXT: RESOURCE.TEXT12,
                    SUB_MENU_TEXT1: 'ASN ' + RESOURCE.TEXT12,
                    SUB_MENU_TEXT2: 'Item ' + RESOURCE.TEXT12
                },
                QC: {
                    QC_TEXT: RESOURCE.TEXT13,
                    SUB_MENU_TEXT1: RESOURCE.TEXT16,
                    SUB_MENU_TEXT2: 'History'
                },
                PUT: {
                    PUT_TEXT: 'Put away',
                    SUB_MENU_TEXT1: RESOURCE.TEXT23,
                    SUB_MENU_TEXT2: 'History'
                },
                RULE: {
                    RULE_TEXT: 'Rule',
                    SUB_MENU_TEXT1: 'Create',
                    SUB_MENU_TEXT2: 'List'
                },
                PICK: {
                    PICK_TEXT: 'Pick',
                    SUB_MENU_TEXT1: 'Get',
                    SUB_MENU_TEXT2: 'Create',
                    SUB_MENU_TEXT3: 'Listing'
                },
                PACK: {
                    PACK_TEXT: 'Pack',
                    SUB_MENU_TEXT1: 'Create',
                    SUB_MENU_TEXT2: 'Listing'
                },
                RTS: {
                    RTS_TEXT: 'Ready To Ship',
                    SUB_MENU_TEXT1: 'Create',
                    SUB_MENU_TEXT2: 'Listing'
                },
                DISPATCH: {
                    DISPATCH_TEXT: 'Dispatch',
                    SUB_MENU_TEXT1: 'Create',
                    SUB_MENU_TEXT2: 'Listing'
                },
                BATCH: {
                    BATCH_TEXT: RESOURCE.TEXT2,
                    SUB_MENU_TEXT1: RESOURCE.TEXT10 + ' unexpected ' + RESOURCE.TEXT3,
                    SUB_MENU_TEXT2: '',
                    SUB_MENU_TEXT3: RESOURCE.TEXT11 + ' batches'
                },
                INVENTORY: {
                    PRODUCT_TEXT: 'Inventory',
                    SUB_MENU_TEXT1: RESOURCE.TEXT19 + RESOURCE.S,
                    SUB_MENU_TEXT2: RESOURCE.TEXT19 + '-' + RESOURCE.TEXT20 + ' ' + RESOURCE.TEXT21.toLowerCase(),
                    SUB_MENU_TEXT3: RESOURCE.TEXT15 + RESOURCE.S,
                }
            },
            STATUS: {
                IP: 'In Progress ',
                EXP: 'Expected ',
                CRT: 'Created ',
                GIN: 'Received ',
                CMP: 'Inbound Complete ',
                EXR: 'Expired ',
                POR: 'PO Raised ',
                PIK: 'Batch Picked ',
                BRCV: 'Arrived', // Status name is changed 'Batch Received' to 'Arrived'
                BCAN: 'Batch Cancelled ',
                RCV: 'Receiving in Progress ',
                CAN: 'Cancelled ',
                REJ: 'PO Rejected by Vendor ',
                ITR: 'Received',
            },
            SOURCE: {
                UE: 'Unexpected'
            },
            BATCH_STATUS: {
                POR: 'PO Raised',
                CRT: 'Created',
                PIK: 'Batch Picked',
                BRCV: 'Batch Arrived', // Status name is changed 'Batch Received' to 'Arrived'
                BCAN: 'Batch Cancelled',
                RCV: 'Receiving in Progress',
                GIN: 'Received',
                CMP: 'Inbound Complete',
                EXR: 'Expired',
                CAN: 'Cancelled',
                REJ: 'PO Rejected by Vendor',
                IP: 'In Progress',
                EXP: 'Expected',
                ITR: 'Received',
                QCD : 'Received'
            },

            ITEM_STATUS: {
                RCV: 'Received',
                ACC: 'Accepted',
                REJ: 'Rejected',
                TBQ: 'To Be Quarantined',
                STK: 'Stocked',
                TBP: 'To Be Picked',
                PIK: 'Picked',
                PAK: 'Packed',
                RTS: 'Ready to Ship',
                SHP: 'Shipped',
                OUT: 'Item Returned',
                RTV: 'RTV',
                RTO: 'RTO',
                HLD: 'Hold',
                DIS: 'Disposed',
                LST: 'Lost',
                JNK: 'Junk',
                EXP: 'Expired',
                PFP: 'Picked For Packing',
                RWR: 'Return Waybill Recieved',
                RPO: 'Return PO Created',
                CD: 'Cross Dock',
                ALC : 'Allocated'
            },
            ACTIVITY_LIST: {
              QC: 'Quality Check',
              ACC: 'Accept',
              REJ: 'Reject',
              TBQ: 'To Be Quarantine',
              PIK: 'Pick',
              PACK: 'Pack',
              RF: 'Road Form'
            },
            PAGE_TITLE: {
                F_PASS_PAGE: {
                    FORGOT_PASSWORD: 'Godam | Forgot Password',
                },
                FC_PAGE : {
                    FC : 'Godam | Fulfillment Services'
                },
                STATION : {
                    SELECT : 'Godam | Select Station'
                },
                RCV : {
                    CRE_ASN : 'Godam | ASN | Create',
                    ASN : 'Godam | Receiving | ASN',
                    ASN_DETAIL : 'Godam | Receiving | ASN | Details',
                    SEARCH_BATCH : 'Godam | Receiving | Batch',
                    BATCH_DETAIL : 'Godam | Receiving | Batch | Details',
                    RCV_SHIP : 'Godam | Receiving | Shipment',
                    RCV_ITEM : 'Godam | Receiving | Item'
                },
                RULE : {
                    SRCH_RL : 'Godam | Rule | List',
                    CREAT_RL : 'Godam | Rule | Create',
                    UPDATE_RL : 'Godam | Rule | Update'
                },
                TITLE1: 'Godam' + ' | ' + RESOURCE.TEXT1 + ' | ' + RESOURCE.TEXT10,
                TITLE2: 'Godam' + ' | ' + RESOURCE.TEXT1 + ' | ' + RESOURCE.TEXT11 + ' ' + RESOURCE.TEXT1,
                TITLE3: 'Godam' + ' | ' + RESOURCE.TEXT1 + ' | Detail',
                TITLE4: 'Godam' + ' | ' + RESOURCE.TEXT1 + ' | ' + RESOURCE.TEXT3 + ' History',
                TITLE5: 'Godam' + ' | ' + RESOURCE.TEXT12 + ' | Shipment ' + RESOURCE.TEXT12,
                TITLE6: 'Godam' + ' | ' + RESOURCE.TEXT12 + ' | Item ' + RESOURCE.TEXT12,
                TITLE7: 'Godam' + ' | ' + RESOURCE.TEXT2 + ' | ' + RESOURCE.TEXT10 + ' Unexpected',
                TITLE8: 'Godam' + ' | ' + RESOURCE.TEXT2 + ' | ' + RESOURCE.TEXT11,
                TITLE9: 'Godam' + ' | ' + RESOURCE.TEXT15 + ' | ' + RESOURCE.TEXT13,
                TITLE10: 'Godam' + ' | ' + 'Put away | Item',
                TITLE11: 'Godam' + ' | ' + 'Put away | Management',
                TITLE12: 'Godam' + ' | ' + RESOURCE.TEXT2 + ' | Detail',
                TITLE13: 'Godam' + ' | Product | Item',
                TITLE14: 'Godam' + ' | Product | List',
                TITLE15: 'Godam' + ' | ' + RESOURCE.TEXT19 + ' | ' + RESOURCE.TEXT20 + ' ' + RESOURCE.TEXT21,
                PAGE_404 : 'Godam | 404'
            },
            BRD_CM: {
                RCVING : {
                    RCV : 'Receiving',
                    CRE_ASN : 'Create ASN',
                    ADD_PROD : 'Add products',
                    ASN_SUMMARY : 'ASN summary',
                    SEARCH_ASN_BATCH : 'ASN',
                    BATCH : 'Batches',
                    ASN_DEATILS : 'ASN details',
                    BATCH_DETAILS : 'Batch details',
                    RCV_SHIP: 'Receive incoming shipment',
                    RCV_ITEM: 'Receive arrived items',
                },

                QCPAGE : {
                    QC : 'Quality check',
                    ACC_MULTI_ITEM : 'Accept multiple item'
                },
                PUTPAGE : {
                    PUT_AWAY : 'Put away'
                },
                RULEPAGE : {
                  RULE : 'Rule',
                  CRE : 'Create',
                  UPDATE : 'Update'
                },

                2: {
                    1: RESOURCE.TEXT11 + ' ' + RESOURCE.TEXT1
                },
                3: {
                    1: RESOURCE.TEXT10 + ' unexpected ' + RESOURCE.TEXT3,
                    2: 'Add unexpected products to ' + RESOURCE.TEXT1,
                    3: 'Unexpected ' + RESOURCE.TEXT3 + ' summary'
                },
                4: {
                    1: RESOURCE.TEXT11 + ' batches',
                },
                5: {
                    1: 'Items',
                    2: 'Item details',
                    3: 'Item changelog'
                },
                6: {
                    1: RESOURCE.TEXT19 + RESOURCE.S,
                    2: 'Product details',
                    3: 'Product changelog',
                    4: 'Channel-wise mapping of product',
                    5: 'Edit product',
                    6: 'Inventory',
                    7 :'Component product details'
                },
                7: {
                    1: RESOURCE.TEXT19 + '-' + RESOURCE.TEXT20 + ' ' + RESOURCE.TEXT21.toLowerCase()
                }
            },
            ALERT_MSG: {
                SUCC_HEAD: 'Success!',
                INFO_HEAD: 'Info!',
                WARNING_HEAD: 'Warning!',
                ERROR_HEAD: 'Error!'
            },
            SUCC_MSG: {
                MSG0: 'has been cancelled.',
                MSG1: ' has been created successfully.',
                MSG2: ' has been marked as "Arrived".',
                QC_REJ: 'Item <serial> has been rejected successfully.',
                QC_ACC: 'Item <serial> has been accepted successfully.',
                QC_TBQ: 'Item <serial> has been put in quarantine successfully.',
                QC_ACC_MULTI: '<qty> items have been accepted successfully.',
                MSG7: 'Password has been reset successfully. <br/>Login with your new password.',
                MSG8: 'Batch has been marked as received successfully.',
                MSG9: 'has been put in location',
                MSG10: 'Attribute values changed successfully!',
                BATCH : 'Batch',
                RCV_BATCH : 'batch is received successfully.',
                IN_ASN : 'in ASN',
                QC_REJ_MULTI : '<qty> items have been rejected successfully.',
                QC_TBQ_MULTI : '<qty> items have been put in quarantine successfully.',
                RULE_CREATE_SUCCESS: 'Rule Created successully.',
                RULE_UPDATE_SUCCESS: 'Rule has been updated successully.'
            },
            ERR_MSG: {
                MSG1: 'Given serial number has been checked already.',
                MSG2: 'Given serial number is invalid. ',
                MSG3: 'Please enter Item serial number.',
                MSG4: 'Given serial number has been added already in the list',
                MSG5: 'You have crossed the maximum scan limit!',
                MSG6: 'Oh snap!',
                MSG7: ' could not be accepted due to some error',
                MSG8: ' No record found against ' + RESOURCE.TEXT1 + ' ' + RESOURCE.TEXT4 + ': ',
                MSG9: 'Reset password link is not valid.',
                MSG10: ' to reset your password again.',
                MSG11: 'Product quantity should be greater than zero for product name ',
                MSG12: 'Please enter location',
                MSG13: 'Should be 14 - 15 digits',
                MSG14: 'No detail found.',
                MSG15: 'PCMS authentication credentials were not provided.',
                NO_DEFAULT_LANDING : 'No default landing page selected.',
                ALLREADY_STATE : 'This batch status is',
                EMAIL_TOO_LONG: 'Email address too long.',
                VALID_EMAIL: 'Enter a valid email. For example, xyz@xyz.com',
                ITEM_IN_LIST : 'This item already in list.',
                ITEM_DETAIL_NOT_FOUND : 'Item details not found against given serial number.',
                PROD_DETAIL_NOT_FOUND : 'Product details not found against given serial number.',
                PCMS_DETAIL_NOT_FOUND : 'PCMS details not found against given serial number.',
                MLP_DETAIL_NOT_FOUND : 'Management lookup details not found against given serial number.',
                RULE_NOT_FOUND : 'Rules not found against given serial number.',
                IS_NOT_VALID : 'is not valid.'

            },
            WARN_MSG: {
                MSG1: 'This item belongs to ',
                MSG2: ' You will be told to check other items belonging to the same order after having marked this item.',
                MSG3: ' You can scan any of the other items in the order:',
                MSG4: 'You cannot scan any other item for now.',
                MSG5: 'This Serial number already Put Away on this Loaction'
            },
            INFO_MSG: {
                IMSG1: 'Review the products you have added here. ASN will be created in the next step. Go back to make any changes.',
                IMSG2: 'Review the products you have added here. The unexpected batch will be created in the next step. Go back to make any changes.',
                IMSG3 : 'No batch found against this ASN :',
                IMSG4 : 'No component product found against this Product Number :'
            },

            PAGE_CONTENT: {
                F_PASS_PAGE: {
                    HEAD1: 'Please enter your Email address.',
                    HEAD2: 'A link to reset your password will be sent to this address.',
                    MAIL_SENT: 'Password reset mail sent!',
                },
                FC_PAGE: {
                    HELLO: 'Hello',
                    CON1: 'Which Fulfilment Centre are you working in?',
                },
                STATION : {
                    CON1 : 'Which station are you working from?',
                    CON2 : 'If you are typing in the batch number, press Enter to submit',
                },
                QCPAGE : {
                    CON1 : 'If you are typing in the serial number, press Enter to submit',
                    CON2 : 'Acceptable items with same Product number'
                },
                PUTAWAY_PAGE : {
                    CON1 : 'Put away',
                    CON2 : 'If you are typing in the location number, press Enter to submit',
                    M_CON1 : 'This item has already been put away at location',
                    M_CON2 : 'You are now requesting to put this item in location:',
                    ARE_U_SURE : 'Are you sure?'
                },
                1: {
                    HEAD1: 'Create an unexpected ' + RESOURCE.TEXT1 + ' under an ' + RESOURCE.TEXT1 + ' only if:',
                    HEAD1_SUB1: '1. The quantity of products sent in the shipment exceeds the expected quantity mentioned in the ' + RESOURCE.TEXT1,
                    HEAD1_SUB2: '2. A product which is not mentioned in the ' + RESOURCE.TEXT1 + ' has been sent',
                    SUB_TITLE: 'Showing all relevant ASN with the above source number'
                },
                2: {
                    HEAD1: 'WAREHOUSING DATA',
                    HEAD2: 'PRODUCT INFORMATION',
                    HEAD3: 'ATTRIBUTES CAPTURED DURING INBOUND',
                },
                3 : {
                    CONTENT1 : 'Disclaimer: This document is only a confirmation of the quantities received of the goods in the list above and does not certify or confirm the contents or the merchantability of the goods in any way.',
                    CONTENT2 : 'Page 1 of 1',
                    CONTENT3 : 'copy',
                    CONTENT4 : 'Delhivery'
                },
                RCV : {
                    ITEM : {
                        CON1 : 'If you are typing in the batch number, press Enter to submit'
                    },
                    SHIPMENT : {
                        CON1 : 'To find the source number, check the document that came along with the shipment. Look for the terms Purchase Order no./ PO no./ STN no./ Order no./ Invoice no.',
                        CON2 : 'Matching expected shipments',
                        CON3 : 'Look for the terms Invoice Order no./ Ref no. in addition to the source number you provided above'
                    }
                }

            },
            GENERIC_PAGE_CONTENT : {
                ERROR404_HEAD : 'ERROR 404',
                ERROR404_MSG : 'Its looking like you may have taken a wrong turn. Dont worry... It happens to the best of us.'
            },
            LABEL_TEXT: {
                QC: 'Quality Check',
                QUARANTINE: 'Quarantine',
                ACCEPT: 'Accept',
                REJECT: 'Reject',
                PICK: 'Pick',
                PACK: 'Pack',
                ROAD_FORM: 'Road Form',
                INPUT_CONTROLS: 'Input Controls',
                ACTIONS: 'Actions',
                ENTER: 'Enter',
                TEXT1: RESOURCE.TEXT1,
                TEXT1_NUM: RESOURCE.TEXT1 + ' ' + RESOURCE.TEXT4,
                TEXT2: RESOURCE.TEXT2,
                TEXT2_NUM: RESOURCE.TEXT2 + ' ' + RESOURCE.TEXT4,
                CLIENT_STORE: RESOURCE.TEXT5 + ' ' + RESOURCE.TEXT6,
                PRIORITIES: 'Priorities',
                OPTIONAL_FIELDS: 'Optional Fields',
                MAND_FIELDS: 'Mandatory Fields',
                INSTRUCTIONS: 'Instructions',
                REASONS: 'Reasons',
                PACK_BOX_NUMBER: 'Pack Box Number',
                FIELDS: 'Fields',
                IS: 'Is',
                MANDATORY: 'Mandatory',
                FIELDS_TO_CAPTURE: 'Fields to Capture',
                CLIENT: RESOURCE.TEXT5,
                ITEM_COUNT: 'Item count',
                SCAN_LABEL_TEXT: 'Scan each item before putting it in the location.<br> You can put multiple items in this location, if there is space.',
                ITEM_PUT_AWAY: 'Items put away:',
                SEARCH_BY_USER: 'Search by user ID ',
                PUT_AWAY_LIST_TEXT: 'Showing list of items put away today',
                USER_ID: 'User ID',
                TIMESTAMP: 'Timestamp',
                LOCATION_SCAN: 'Scan the label of the location where you want to put the item',
                TEXT3: 'Order',
                USUAL: 'Usual',
                BATCH_CRE_BY: 'Batch created by',
                NATURE_OF_DEL: 'Batch type',
                AVAIL_TEXT: 'Availability',
                SUPPLIER: RESOURCE.TEXT8,
                SUPPLIER_STORE: RESOURCE.TEXT8 + ' ' + RESOURCE.TEXT6,
                WARN_TEXT: RESOURCE.TEXT17,
                VENDOR: 'Vendor',
                TEXT1_DEATIL: RESOURCE.TEXT1 + ' details',
                TEXT2_DEATIL: RESOURCE.TEXT2 + ' details',
                SHIP_NUM: 'Shipment ' + RESOURCE.TEXT4,
                PROD: 'Product',
                PRODS: 'Products',
                PROD_NAME: 'Product name',
                PROD_TYPE: 'Product type',
                PCM_ID: 'PCMS ID ',
                DCM_ID: 'DCMS ID',
                PROD_DESC: 'Product description',
                PROD_NUM: 'Product ' + RESOURCE.TEXT4,
                SKU: 'SKU',
                SKU_NUM: 'SKU ' + RESOURCE.TEXT4,
                QT: 'Quantity',
                QTY_PCS: 'Quantity (pcs)',
                STATUS: 'Status',
                STATUS2: 'status',
                CUR_STATUS: 'Current status',
                DATE_RANGE: 'Date range',
                VALIDITY: 'Validity',
                EXPIRED: 'Expired',
                ACTIVE: 'Active',
                ACTIVITY: 'Activity',
                INACTIVE: 'Inactive',
                BOTH: 'All',
                EXPIRE_ON: 'Expiry on',
                CRE_AT: 'Created at',
                CRE_ON: 'Created on',
                CRE_BY: 'Created by',
                RCV: 'Received',
                RCV_ON: 'Received on',
                SHIP_ON: 'Shipped on',
                PACK_ON: 'Packed on',
                PICK_ON: 'Picked on',
                STOCK_ON: 'Stocked on',
                ACCEPT_ON: 'Accepted on',
                QC_ON : 'Quality Checked on',
                IB_COM_ON: 'Inbound completed on',
                TEXT1_CRE_AT: RESOURCE.TEXT1 + ' created at',
                TEXT1_CRE_ON: RESOURCE.TEXT1 + ' created on',
                TEXT1_CRE_BY: RESOURCE.TEXT1 + ' Created by',
                TEXT1_EXP_DATE: RESOURCE.TEXT1 + ' expiry date',
                TEXT1_RCV_ON: RESOURCE.TEXT1 + ' received on',
                TEXT1_IB_COM_ON: RESOURCE.TEXT1 + ' inbound completed on',
                EXP: 'Expected',
                UNEXP: 'Unexpected',
                QC_ACC: 'QC Accepted',
                QC_REJ: 'QC Rejected',
                ACC: 'Accepted',
                REJ: 'Rejected',
                QTY_AVL: 'Qty available',
                QTY_IN_HAND: 'Qty in hand',
                QTY_HELD: 'Qty held',
                HOLD: 'Hold',
                ON_HOLD: 'On Hold',
                ITEM_ACC: 'Items accepted',
                ITEM_RCV: 'Items received',
                ITEM_EXP: 'Items expected',
                ITEM: RESOURCE.TEXT15,
                ITEMS_TEXT: 'Items',
                ARR_ON: 'Arrived on',
                CUR_EXP_TEXT2: 'Current expected ' + RESOURCE.TEXT3,
                FILTER: 'FILTERS',
                CHOOSE: 'Any',
                DOWNLOAD_REPORT: 'Download report',
                LINK1: 'Default',
                LINK2: 'Detail',
                LINK3: 'SUMMARIZED',
                LINK4: 'View status history',
                LINK5: 'See batch history',
                MRP_PER_POINT: 'MRP per unit',
                TYPE: 'Type',
                BH: RESOURCE.TEXT3 + ' history',
                CHECK_ITEM_TEXT: RESOURCE.TEXT16,
                QC : 'Quality check',
                ACCEPT_MULTIPLE_ITEM: 'Accept multiple items',
                SERIAL_NUM: RESOURCE.TEXT18,
                ITEM_TEXT: RESOURCE.TEXT15,
                CHECK_FOR_ITEM: 'Check the color, finish and look of the product:',
                CHECK_ITEM_FROM_MARKETPLACE: 'Check product details from the marketplace:',
                MATCH_PROD_DETAIL: 'Match these details with the label on the product packaging: ',
                MEASURE_FOR_ITEM: ' Measure and check/update the following information:',
                QC_ITEM_INST: 'Do not forget to check the following: ',
                QUARANTINE_TEXT: 'Quarantine',
                ACC_TEXT: 'Accept',
                ACC_MULTIPLE: 'Accept Multiple',
                REASON_REJECT: 'Why do you want to reject this item?',
                REASON_MULTI_REJECT: 'Why do you want to reject these item?',
                CHOOSE_REASON: 'Choose reason',
                CHOOSE_UNIT: 'Choose unit',
                REASON_NOT_IN_LIST: 'Reason not mentioned in the list',
                REASON_QUARANTINE: 'Why do you want to quarantine this item?',
                REASON_MULTI_QUARANTINE: 'Why do you want to quarantine these item?',
                ACCEPT_ALL: 'Accept all',
                ITEM_SCAN_MULTIPLE: 'Items of the same product which are acceptable ',
                SERIAL_TEXT: 'Serial',
                SERIALS_TEXT : 'Serials',
                SEARCH_BY : 'Search by:',
                SEARCH_BY_ASN: 'Search by ASN',
                SEARCH_BY_CLIENT: 'Search by client store',
                SEARCH_RESULT : 'Search results:',
                NOT_VALID : 'not valid',
                PUT_ITEM: 'Put items',
                TO_LOST: 'to Lost',
                TO_HOLD: 'to Hold',
                TO_REJECT: 'to Reject',
                TO_JUNK: 'to Junk',
                PROD_SKU: 'Product SKU',
                SUPPLIER_SKU: 'Supplier SKU',
                FLOW: 'Flow',
                DESCRIPTION: 'Description',
                OPTIONAL : 'Optional',
                CATEGORY: 'Category',
                COMBO: 'Combo',
                URL: 'URL',
                PICKLIST_ID: 'Picklist ID',
                LOCATION: 'Location',
                IMEI: 'IMEI',
                IMEI_REQ : 'IMEI required?',
                MRP: 'M.R.P',
                INR: 'INR',
                USD: 'USD',
                EURO: 'EURO',
                IN_INR: 'In INR',
                IN_CM: 'In cm',
                IN_GM: 'In gm',
                IN_KG: 'In kg',
                CM : '(cm)',
                GM : '(gm)',
                KG : '(kg)',
                WT: 'Weight',
                HT: 'Height',
                WD: 'Width',
                LT: 'Length',
                EXP_DATE: 'Expiry date',
                TIMES_TAMP: 'Timestamp',
                USER_NAME: 'User name',
                ORDER_LINE: 'Orderline',
                CHANGE: 'Change',
                CHANGES: 'Changes',
                COMMENTS: 'Comments',
                REVIEWED_BY: 'Reviewed by',
                ACTION: 'Action',
                REVIEWED_AT: 'Reviewed at',
                CHANNEL: 'Channel',
                SELLER_SKU: 'Seller SKU',
                SELLER_SKU_CHANNEL: 'Seller SKU on channel',
                CHANNEL_SKU: 'Channel SKU',
                LID: 'Listing ID',
                ALLOCATION: 'Allocation',
                MASTER_CHANNEL_URL: 'Master channel URL',
                CURRENCY: 'Currency',
                DIMENSION_UNIT: 'Dimension unit',
                ATTRIBUTES: 'ATTRIBUTES',
                MEASR_ATTR : 'Measurable attributes',
                TCNSC: 'TAGGED CATEGORIES & SUB-CATEGORIES',
                APPROVED: 'Approved',
                TO_BE_REVIEWED: 'To be reviewed',
                AVAILABILITY: 'Availability',
                SET_AVAIL: 'Set availability',
                SET_VAL: 'Set value',
                EDIT_PROD_ALLOC: 'Edit product allocation on a channel',
                EDIT_PROD_AVAIL: 'Edit product availability on a channel',
                EDIT_ALLOC: 'Edit allocation',
                EDIT_AVAIL: 'Edit availability',
                PERCENT : '%',
                PCS : 'pcs',
                SEE_ITEM : 'See items in this batch',
                S_NO : 'S.No',
                NUMBER : 'Number',
                PO_QUAN : 'PO Quantity',
                TOTAL_VALUE : 'Total Value',
                RCV_QUAN : 'Received Quantity',
                REMARK : 'Remarks',
                STN : 'Stock Transfer Note',
                PO : 'PO #',
                TO : 'TO',
                FROM : 'From',
                CONTACT : 'Contact',
                EMAIL : 'Email',
                TOTAL_NUMBER : 'Total Number',
                PRO_EXE : 'Procurement Executive',
                WARE_SUPER : 'Warehouse Supervisor',
                SIGNSEAL : 'Sign & Seal',
                S_TEXT : RESOURCE.S,
                CLK_TO_VIEW : 'Click to view',
                OF : 'of',
                AVIL_ORDER : 'Available for order',
                CMP_PRODUCT : 'Component products',
                EACH_SET : 'Each set',
                EXTRA : 'Extra',
                PROD_INFO : 'Product information',
                ITEM_INFO : 'Item information',
                SMH : 'See modification history',
                SEE_CHANNEL_ALC: 'See channel-wise allocation',
                EAN_REQ : 'EAN required?',
                SN_REQ : 'SN required?',
                REJECTION_DURATION : 'Rejection duration',
                EXP_DATE_REQ : 'Expiry date required?',
                MASTER_PRODUCT : 'Master product',
                SHH : 'See modification history',
                FC_LOC : 'FC Location',
                WAYBILL : 'Waybill',
                DISPATCH_ID : 'Dispatch ID',
                ACD_INBOUND : 'inbound attributes',
                SRC_NUM : 'Source number',
                UNIT_EXP : 'Units expected',
                UNIT_RCV : 'Units received',
                UNIT_ACP : 'Units accepted',
                UNIT_REJ : 'Units rejected',
                ASN_INFO : 'ASN information',
                BATCH_INFO : 'Batch information',
                DOC_NUM : 'Document number',
                BATCH_TO_RCV : 'Batch to be received',
                EXP_PROD : 'Expected products',
                SER_PRINT : 'Serials you printed',
                RCV_CMP : 'Receive components',
                NOT_MORE_THAN : 'Not more than',
                SOURCE_NUM_SHIP : 'Source number of the shipment',
                NO_OF_BOX : 'Number of boxes in the shipment',
                BOX_RCV : 'Boxes you received',
                ADDITIONAL_DOC_NUM : 'Additional document ID no. (optional)',
                BATCHES : 'Batches',
                NO_ITM_BATCH : 'No items found in this batch',
                YOU_RCV : 'You have received',
                ITEM_IN_BATCH : 'items in this batch',
                ENTER_CENTER_CODE: 'Enter center code',
                OPERATIONS : 'OPERATIONS',
                OR : 'or',
                PUT_AWAY : 'PutAway',
                CLICK_LOGIN_TEXT: 'Click here to Login',
                EXTERNEL_BUCKET : 'External bucket',
                INTERNAL_BUCKET : 'Internal bucket',
                ITEM_BE_CHECKED : 'Item to be checked',
                CHECK_PROD_PAGE : 'Check product images',
                SEE_MORE_IMG : 'See more images here:',
                YES_MOVE : 'Yes,move',
                LOCATION_WHERE_ITEM : 'Location where item is to be put',
                SHOW_LATEST_TOP : 'Showing latest added on top',
                NOTE : 'Note :',
                QC_MULTI_NOTE : 'All the items to be rejected/put in quarantine must have the same reason.',
                EDIT : 'Edit',
                VIEW_DETAIL : 'View Details',
                RULE : {
                  FILTER_BY : {
                    ACTIVITY : 'Activity',
                    PRODUCT_CATEGORY : 'Product Category',
                    PRODUCT_TYPE : 'Product Type',
                    PRODUCT_NAME : 'Product Name',
                    MASTER_CHANNEL : 'Master Channel',
                    CLIENT_PARTY : 'Client Party',
                    CLIENT_STORE : ' Client Store',
                    SUPPLIER_PARTY : 'Supplier Party',
                    SUPPLIER_STORE : 'Supplier Store',
                    FULFILMENT_CENTER : 'Fulfillment Center',
                  },
                  MODAL_TITLE : {
                    RULE_DETAIL : 'Rule Details',
                    RULE_CREATE_CONFIRM : 'Rule Create Confirmation',
                    RULE_UPDATE_CONFIRM : 'Rule Update Confirmation'
                  }
                },
                PACK_BOX_NUMBER: 'Pack Box Number',
                EXPRESSION: 'Expressions',
                PRIORITY: 'Priority',
                SET: 'Set',
                ITEMS_SCANNED: '$$count item(s) scanned'
            },
            KEY_PRESS_LABEL: {
                ALT_R_TEXT: 'Press ALT + R Key',
                ALT_Q_TEXT: 'Press ALT + Q Key',
                ALT_M_TEXT: 'Press ALT + M Key',
                ALT_A_TEXT: 'Press ALT + A Key',
                ALT_ENTER_TEXT: 'Press ALT + ENTER Key',
                ESC_KEY : 'Press ESC Key',
                CTRL_ENTER_KEY: 'Press CTRL + ENTER Key'
            },
            INPUT_TEXT: {
                ENTER_MASTER_CHANNEL: 'Enter ' + RESOURCE.TEXT25 + ' ' + RESOURCE.TEXT26 + ' name',
                ENTER_SUPPLIER_PARTY: 'Enter ' + RESOURCE.TEXT9 + ' ' + RESOURCE.TEXT24 + ' name',
                ENTER_CLIENT_PARTY: 'Enter ' + RESOURCE.TEXT7 + ' ' + RESOURCE.TEXT24 + ' name',
                ENTER_CLIENT_STORE: 'Enter ' + RESOURCE.TEXT7 + ' ' + RESOURCE.TEXT6 + ' name',
                ENTER_LOCATION: 'Scan/Enter location number',
                ENTER_SERIAL_NUM: 'Scan/Enter item serial number to see checking parameters',
                ENTER_MULTIPLE_SCAN_ITM: 'Scan/Enter item serial number to add to list',
                ENTER_PICK_ID : 'Enter picklist id',
                ENTER_NUM: 'Enter number',
                ENTER_COMMA : 'Enter comma separated no.',
                ENTER_NAME : 'Enter name',
                ENTER_SUPPLIER_STORE: 'Enter ' + RESOURCE.TEXT9 + ' ' + RESOURCE.TEXT6 + ' name',
                ENTER_VENDOR: 'Enter vendor name',
                ENTER_SHIP_NUM: 'Enter shipment ' + RESOURCE.TEXT4,
                ENTER_TEXT1: 'Enter ' + RESOURCE.TEXT1 + ' ' + RESOURCE.TEXT4,
                ENTER_TEXT2: 'Enter ' + RESOURCE.TEXT2 + ' ' + RESOURCE.TEXT4,
                ENTER_COUNT: 'Enter count',
                ENTER_AMOUNT : 'Enter amount',
                ENTER_BOXES: 'No. of boxes/pallets received',
                PROD_SKU: 'Product/SKU',
                SEARCH_PROD_SKU: 'Search by Product/SKU',
                ADD_PROD: 'Add this product',
                ADD_PROD1: 'Add product',
                ADD_PRODS: 'Add products',
                NEXT: 'Next',
                SEARCH: 'Search',
                CANCEL: 'Cancel',
                BACK: 'Back',
                BACK_ADD_PROD: 'Back to add products',
                PRINT_BATCH: 'Print batch number',
                PRINT_SERIAL: 'Print serial',
                REPRINT: 'Reprint last set of serials',
                REPRINT_BARCODE : 'Reprint last set of barcodes',
                DONE: 'Done',
                ACCEPT_SHP: 'Accept Shipment',
                CRE_TEXT1: 'Create this' + ' ' + RESOURCE.TEXT1,
                CAN_TEXT1: 'Cancel ' + RESOURCE.TEXT1,
                DD_MM_YYYY: 'YYYY-MM-DD - YYYY-MM-DD',
                REVERT: 'Revert',
                SCAN_TEXT2: 'Scan/Enter batch number on box/pallet to see expected items',
                EXP_DATE: 'Expiry date',
                CRE_TEXT2: 'Create this' + ' ' + RESOURCE.TEXT3,
                MARK_RCV: 'Mark as received',
                ENTER_REASON: 'Enter reason here',
                SCAN_SERIAL: 'Scan/Enter serial number',
                EDIT_ATTR: 'Edit attributes',
                EDIT_PROD: 'Edit product',
                SAVE_CHANGE: 'Save changes',
                SEE_CHANGELOG: 'See changelog',
                CHANGE_STATUS: 'Change status',
                ENTER_MRP: 'Enter MRP',
                ENTER_HEIGHT: 'Enter height',
                ENTER_LENGTH: 'Enter length',
                ENTER_WIDTH: 'Enter width',
                ENTER_URL: 'Enter URL',
                ENTER_VALUE : 'Enter value',
                ENTER_DATE : 'Enter date',
                SEE_CHANNEL_MAPPING: 'See channel-wise mapping',
                PERCENTAGE: 'Percentage (%)',
                QTY_PCS: 'Quantity (pcs)',
                DOWNLOAD_CSV : 'Download .csv',
                EDIT : 'Edit',
                SAVE : 'Save',
                SEARCH_NAM_NUM : 'Search by name/number',
                FINISH_BATCH : 'Finish receiving this batch',
                RCV : 'Receive',
                FINISH : 'Finish',
                SCAN_STATION : 'Scan/Enter station number to start receiving',
                FORGOT_PASSWORD: 'Forgot your password?',
                BACK_LOGIN : 'Back to login',
                ENTER_FULFILMENT_CENTER : 'Enter fulfilment center',
                ENTER_EMAIL : 'Enter email',
                REJECT: 'Reject',
                QUARANTINE : 'Quarantine',
                REJECT_ALL: 'Reject all',
                QUARANTINE_ALL : 'Quarantine all',
                CHANGE_LOC : 'Change location',
                MOVE_TO_NEXT_LOC : 'Move to next location',
                LINK_GO_BACK_DASHBOARD : 'Back to dashboard',
                CHECK_MULTI_ITEMS : 'Check multiple items',
                ENTER_CAT : 'Enter category',
                ENTER_TYPE : 'Enter type'
           },

            RESULT_TEXT: 'result',
            RESULTS_TEXT: 'results',
            PROD_TEXT: 'Product',
            PRODS_TEXT: 'Products',
            BTN_CANCEL: 'Cancel',
            BTN_FINISH: 'Finish',
            BTN_CLOSE: 'Close',
            BTN_CONFIRM: 'Confirm',
            BTN_PREV: 'Prev',
            BTN_NEXT: 'Next',
            BTN_DONE: 'Done',
            BTN_SAVE: 'Save',
            YES: 'Yes',
            NO: 'No',
            HOME_TEXT: 'Home',
            BTN_START: 'Start',
            H1: RESOURCE.TEXT0,
            BTN_LOGIN_TEXT: 'Login',
            BTN_CONTINUE_TEXT: 'Continue',
            PLZ_TEXT: 'please',
            BTN_CLICK: 'Click Here',
            BTN_LOGIN_TEXT_D: 'Login with Delhivery ID',
            BTN_SUBMIT: 'Submit',
            NO_RECORD: 'No record found.',
            LAUNCH: 'Launch',
            USER_NAME_TEXT: 'Username',
            PASSWORD_TEXT: 'Password',
            BTN_REJECT: 'Reject',
            BTN_RESET_PASS: 'Reset Password',
            ERR1: 'Must contain one lower &amp; uppercase letter, and one non-alpha character (a number or a symbol.)',
            ERR2: 'Password must be between 8 and 20 characters.',
            ERR3: 'Some error occurred. Please try again later',
            ERR4: 'Please enter batch ' + RESOURCE.TEXT4,
            ERR5: RESOURCE.TEXT1 + ' ' + RESOURCE.TEXT4 + ' is not found',
            COMPANY_NAME: 'SSN Logistics Pvt Ltd, 2014',
            ERR6: 'Product quantity should be greater than : 0.',
            ERR7: 'Entered quantity should not be more than available quantity',
            ERR8: 'Please enter batch number'
        }
    });
